#!/usr/bin/env bash

# General
set-environment -g TMUX_PLUGIN_MANAGER_PATH "$HOME/.local/share/tmux/plugins"

# Bootstrap
if "test ! -d ~/.local/share/tmux/plugins" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.local/share/tmux/plugins/tpm && ~/.local/share/tmux/plugins/tpm/bin/install_plugins'"

# Continuum
set -g @continuum-restore 'on'

# Sessionx
set -g @sessionx-bind 'o'

