#!/usr/bin/env bash
# Tokyo Night for Tmux

BG="#24283b"
BG_DARK="#1f2335"
BG_HL="#292e42"

FG="#c0caf5"
FG_DARK="#a9b1d6"
FG_GUTTER="#3b4261"

BLUE="#7aa2f7"
CYAN="#7dcfff"
GREEN="#9ece6a"
MAGENTA="#ff007c"
ORANGE="#ff9e64"
PURPLE="#9d7cd8"
RED="#f7768e"
TEAL="#1abc9c"
YELLOW="#e0af68"

set -g mode-style "fg=${FG},bg=${BG}"

set -g message-style "fg=${BG},bg=${GREEN}"
set -g message-command-style "fg=${BLUE},bg=${FG_GUTTER}"

set -g pane-border-style "fg=#3b4261"
set -g pane-active-border-style "fg=${RED}"

set -g status "on"
set -g status-justify "centre"

set -g status-style "fg=${FG},bg=${BG}"

set -g status-left-length "100"
set -g status-right-length "100"

set -g status-left-style NONE
set -g status-right-style NONE

set -g status-left "#[fg=${YELLOW},bg=${BG},bold] #[fg=${BG},bg=${YELLOW},bold] #S #[fg=${YELLOW},bg=${BG},bold] "
set -g status-right ""

setw -g window-status-activity-style "underscore,fg=${FG},bg=${BG}"
setw -g window-status-separator " "
setw -g window-status-style "NONE,fg=${FG},bg=${FG_GUTTER}"
setw -g window-status-format "#[fg=${FG_GUTTER},bg=${BG},bold]#[default] #I | #W #[fg=${FG_GUTTER},bg=${BG},bold]"
setw -g window-status-current-format "#[fg=${PURPLE},bg=${BG}]#[fg=${BG},bg=${PURPLE},bold] #I | #W #[fg=${PURPLE},bg=${BG}]"
